# Дерево/однотонный декор: бесшовный фрагмент листа -> растровая плитка (base64 JPEG) для src/decorTiles.js.
# Использование: python bake_tile.py <board_orig.png> <period_x_px> <period_y_px> <tileMM> <size> <quality> <out decorTiles.js> <code1,code2,...>
# Волокно в изображении листа идёт вдоль длинной стороны (вертикально) -> плитка поворачивается на 90°,
# чтобы волокно шло вдоль оси x текстуры (как у woodTexture() во viewer.js).
# H1145 ST10: python bake_tile.py board_orig.png 3685 3684 1300 1536 65 ../../src/decorTiles.js LINK-1790014004794,CTOP-LDSP38-H1145ST10
import sys, io, base64
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
src, px, py, mm, size, q, out, codes = sys.argv[1:9]
im = Image.open(src).convert('RGB').crop((0, 0, int(px), int(py))).rotate(90, expand=True)
im = im.resize((int(size), int(size)), Image.LANCZOS)
b = io.BytesIO(); im.save(b, 'JPEG', quality=int(q), optimize=True)
d = base64.b64encode(b.getvalue()).decode()
js = ("/* GENERATED by tools/texture-convert/bake_tile.py: бесшовная плитка декора из листа производителя. Не править руками. */\n"
      "(function(){'use strict';var r=window.Modul3D=window.Modul3D||{};var t={tileMM:%s,src:'data:image/jpeg;base64,%s'};"
      "r.decorTiles={byCode:{%s}};})();\n") % (mm, d, ','.join("'%s':t" % c for c in codes.split(',')))
open(out, 'w', encoding='utf-8').write(js)
print(len(b.getvalue()) // 1024, 'KB jpeg', len(js) // 1024, 'KB js')
