# Дерево/однотонный/мраморный декор: бесшовный фрагмент листа -> растровая плитка (base64 JPEG) для src/decorTiles.js.
# Использование: python bake_tile.py <board_orig.png> <period_x_px> <period_y_px> <tileMM> <size> <quality> <out decorTiles.js> <code1,code2,...>
# Файл out ДОПОЛНЯЕТСЯ: плитки других декоров, уже лежащие в нём, сохраняются (коды из аргумента перезаписываются).
# Рисунок в изображении листа идёт вдоль длинной стороны (вертикально) -> плитка поворачивается на 90°,
# чтобы он шёл вдоль оси x текстуры (как у woodTexture() во viewer.js).
# H1145 ST10: python bake_tile.py board_orig.png 3685 3684 1300 1536 65 ../../src/decorTiles.js LINK-1790014004794,CTOP-LDSP38-H1145ST10
# F206 ST9:   python bake_tile.py egger_full.png 3685 3716 1300 1536 65 ../../src/decorTiles.js LINK-1790249477980,CTOP-COMPACT12-F206ST9
import sys, io, os, re, base64
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
src, px, py, mm, size, q, out, codes = sys.argv[1:9]
im = Image.open(src).convert('RGB').crop((0, 0, int(px), int(py))).rotate(90, expand=True)
im = im.resize((int(size), int(size)), Image.LANCZOS)
b = io.BytesIO(); im.save(b, 'JPEG', quality=int(q), optimize=True)
d = base64.b64encode(b.getvalue()).decode()
new_codes = codes.split(',')

# Уже лежащие в файле плитки: [(mm, base64, [коды])]
tiles = []
if os.path.exists(out):
    old = open(out, encoding='utf-8').read()
    objs = {m.group(1): (m.group(2), m.group(3)) for m in
            re.finditer(r"var (t\d*)=\{tileMM:(\d+),src:'data:image/jpeg;base64,([^']+)'\}", old)}
    by = re.search(r"byCode:\{([^}]*)\}", old)
    pairs = re.findall(r"'([^']+)':(t\d*)", by.group(1)) if by else []
    for name, (omm, od) in objs.items():
        cs = [c for c, n in pairs if n == name and c not in new_codes]
        if cs:
            tiles.append((omm, od, cs))
tiles.append((mm, d, new_codes))

vars_js, map_js = [], []
for i, (tmm, td, cs) in enumerate(tiles):
    n = 't%d' % (i + 1)
    vars_js.append("var %s={tileMM:%s,src:'data:image/jpeg;base64,%s'};" % (n, tmm, td))
    map_js += ["'%s':%s" % (c, n) for c in cs]
js = ("/* GENERATED by tools/texture-convert/bake_tile.py: бесшовная плитка декора из листа производителя. Не править руками. */\n"
      "(function(){'use strict';var r=window.Modul3D=window.Modul3D||{};%s"
      "r.decorTiles={byCode:{%s}};})();\n") % (''.join(vars_js), ','.join(map_js))
open(out, 'w', encoding='utf-8').write(js)
print(len(b.getvalue()) // 1024, 'KB jpeg', len(js) // 1024, 'KB js', len(tiles), 'tiles')
