# Растровые плитки декоров -> src/decorTiles.js (base64 JPEG). Нужны Python 3 и pillow.
# Лист производителя (Egger «Plattenansicht», 2800x1300 мм, волокно/рисунок вдоль длинной стороны) лежит
# вне репозитория в D:\#Project claude\Model3D\texture-sources\<код>_Egger\board_orig.png.
# Из листа берётся квадрат 1300x1300 мм (3685 px по ширине), поворачивается на 90° (рисунок вдоль оси x
# текстуры, как у woodTexture() во viewer.js) и уменьшается до size.
#   mode 'hash'   — плитка периодична (дуб H1145: период = ширина листа) — клетки во вьювере зеркалятся
#                   случайно по хэшу столбца/строки;
#   mode 'mirror' — лист не периодичен (у Egger «ширина без повтора») — клетки зеркалятся ЧЕРЕДОВАНИЕМ,
#                   зеркальный стык всегда непрерывен.
# Для F206 берётся ВЕСЬ лист (py=7937 -> 2800x1300 мм, рисунок не зеркалится в пределах листа).
# Запуск: python bake_tile.py <папка texture-sources> <выход decorTiles.js>
import sys, io, base64, json
import numpy as np
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
SRC, OUT = sys.argv[1], sys.argv[2]
ENTRIES = [
    # папка,        px по y,  size, q,  mode,    коды позиций каталога
    ('H1145_ST10_Egger', 3684, 1536, 65, 'hash',   ['LINK-1790014004794', 'CTOP-LDSP38-H1145ST10']),
    ('H3450_ST22_Egger', 3685, 1024, 72, 'mirror', ['H3450ST22']),
    ('H1330_ST10_Egger', 3685, 1536, 62, 'mirror', ['CTOP-COMPACT12-650']),
    ('F8001_ST9_Egger',  3685, 1024, 72, 'mirror', ['CTOP-COMPACT12-F8001ST9']),
    ('F235_ST76_Egger',  3685, 1024, 72, 'mirror', ['CTOP-LDSP38-920']),
    ('F221_ST87_Egger',  3685, 1024, 72, 'mirror', ['CTOP-COMPACT12-F221ST87']),
    ('F128_PA_Egger',    3685, 1024, 72, 'mirror', ['LINK-1790325008828']),
    ('F206_ST9_Egger',   7937, 2560, 72, 'mirror', ['LINK-1790249477980', 'CTOP-COMPACT12-F206ST9'], 'egger_full.png'),
]
parts, reg = [], []
for i, (d, py, size, q, mode, codes, *fn) in enumerate(ENTRIES):
    import os
    f = '%s/%s/%s' % (SRC, d, fn[0] if fn else 'board_orig.png')
    if not os.path.exists(f): f = f[:-4] + '.jpg'   # F221/F128: полный PNG 52 МБ, взят JPEG той же ширины 3685 px
    im = Image.open(f).convert('RGB').crop((0, 0, 3685, py)).rotate(90, expand=True)
    # py > 3685 — берём лист целиком (не квадрат): size — длинная сторона, tileMM по x = реальная длина листа
    tw, th = size, int(round(size * 3685.0 / py))
    mmx = int(round(py * 1300.0 / 3685))
    im = im.resize((tw, th), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'JPEG', quality=q, optimize=True)
    print(d, len(b.getvalue()) // 1024, 'KB')
    # k — множитель цвета материала во вьювере: яркий декор приглушаем (свет сцены его пережигает), тёмный не трогаем
    L = float(np.asarray(im.convert('L'), np.float32).mean())
    k = round(min(1.0, 0.88 * 170.0 / L), 2)
    parts.append("var t%d={tileMM:%d,tileMM2:1300,sheet:%s,mode:'%s',k:%s,src:'data:image/jpeg;base64,%s'};" % (i, mmx, 'true' if py > 3685 else 'false', mode, k, base64.b64encode(b.getvalue()).decode()))
    reg += ["'%s':t%d" % (c, i) for c in codes]
js = ("/* GENERATED by tools/texture-convert/bake_tile.py: растровые плитки декоров из листов производителя. Не править руками. */\n"
      "(function(){'use strict';var r=window.Modul3D=window.Modul3D||{};%s\nr.decorTiles={byCode:{%s}};})();\n") % ('\n'.join(parts), ','.join(reg))
open(OUT, 'w', encoding='utf-8').write(js)
print(len(js) // 1024, 'KB js')
